spring:
  application:
    name: Libreria Online

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 1                    # Solo 1 conexión
      minimum-idle: 0
      idle-timeout: 10000
      max-lifetime: 300000                    # 5 minutos
      connection-timeout: 10000
      initialization-fail-timeout: 5000       # Falla rápido si no conecta

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate                      # Evita cambios en esquema
    show-sql: true
    open-in-view: false                       # Mejor práctica